add config container

diff --git a/ix-dev/enterprise/syncthing/templates/docker-compose.yaml b/ix-dev/enterprise/syncthing/templates/docker-compose.yaml
--- a/ix-dev/enterprise/syncthing/templates/docker-compose.yaml
+++ b/ix-dev/enterprise/syncthing/templates/docker-compose.yaml
@@ -34,8 +34,105 @@ configs:
     content: {{ values.ix_certificates[values.network.certificate_id].certificate | tojson }}
 {% endif %}
 
+{% set caps = ix_lib.base.security.get_caps(add=["CHOWN", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID", "SETFCAP", "SETPCAP", "SYS_ADMIN"]) %}
+{% set app_env = {
+  "PCAP": ["cap_sys_admin", "cap_chown", "cap_dac_override", "cap_fowner"]|join(",") + "+ep",
+  "STNOUPGRADE": true,
+  "STGUIADDRESS": "0.0.0.0:%d" | format(values.network.web_port),
+  "STGUIASSETS": "/var/truenas/assets/gui",
+} %}
 {# Containers #}
 services:
+  {{ values.consts.config_container_name }}:
+    image: {{ ix_lib.base.utils.get_image(images=values.images, name="image") }}
+    user: "0:0"
+    deploy:
+      resources: {{ ix_lib.base.resources.resources(values.resources) | tojson }}
+    devices: {{ ix_lib.base.resources.get_devices(values.resources) | tojson }}
+    configs:
+      - source: logo-horizontal-svg
+        target: {{ values.consts.logo_horizontal_svg_path }}
+    {% if values.network.certificate_id %}
+      - source: private
+        target: {{ "%s/config/https-key.pem" | format(values.consts.home_path) }}
+      - source: public
+        target: {{ "%s/config/https-cert.pem" | format(values.consts.home_path) }}
+    {% endif %}
+    {% set config_caps = ix_lib.base.security.get_caps(add=caps.add + ["KILL"]) %}
+    cap_add: {{ config_caps.add | tojson }}
+    cap_drop: {{ config_caps.drop | tojson }}
+    security_opt: {{ ix_lib.base.security.get_sec_opts(remove=["no-new-privileges"]) | tojson }}
+    healthcheck:
+      disable: true
+    entrypoint:
+      - /bin/sh
+    {% set config_dir = "%s/config"|format(values.consts.home_path) %}
+    {% set cli = "syncthing cli --home %s config"|format(config_dir) %}
+    {% set st = values.consts.settings %}
+    {% set settings = [
+      {"cmd": "options announce-lanaddresses", "value": 1 if st.announce_lan_addresses else 0, "quote": true},
+      {"cmd": "options global-ann-enabled", "value": 1 if st.global_discovery else 0, "quote": true},
+      {"cmd": "options local-ann-enabled", "value": 1 if st.local_discovery else 0, "quote": true},
+      {"cmd": "options natenabled", "value": 1 if st.nat_traversal else 0, "quote": true},
+      {"cmd": "options relays-enabled", "value": 1 if st.relaying else 0, "quote": true},
+      {"cmd": "options uraccepted", "value": 1 if st.telemetry else 0, "quote": true},
+      {"cmd": "options auto-upgrade-intervalh", "value": st.auto_upgrade_intervalh, "quote": true},
+      {"cmd": "defaults folder xattr-filter max-total-size", "value": st.xattr_filter_max_total_size, "quote": false},
+      {"cmd": "defaults folder xattr-filter max-single-entry-size", "value": st.xattr_filter_max_single_entry_size, "quote": true},
+      {"cmd": "defaults folder send-ownership", "value": st.send_ownership, "quote": false},
+      {"cmd": "defaults folder sync-ownership", "value": st.sync_ownership, "quote": false},
+      {"cmd": "defaults folder send-xattrs", "value": st.send_xattrs, "quote": false},
+      {"cmd": "defaults folder sync-xattrs", "value": st.sync_xattrs, "quote": false},
+      {"cmd": "defaults folder ignore-perms", "value": st.ignore_perms, "quote": false},
+      {"cmd": "defaults folder path", "value": st.path, "quote": true},
+    ] %}
+    command:
+      - -c
+      - |
+        set -e
+        trap cleanup EXIT TERM
+        cleanup() {
+            echo "Gracefully stopping Syncthing..."
+            if kill -0 $$SYNCTHING_PID > /dev/null 2>&1; then
+                kill -SIGTERM $$SYNCTHING_PID
+                wait $$SYNCTHING_PID
+            fi
+            echo "Syncthing stopped."
+        }
+        try_for() {
+            local max_tries=$$1
+            local sleep_time=$$2
+            local cmd=$$3
+            tries=0
+            until eval "$$cmd"; do
+                [ $$tries -ge $$max_tries ] && return 1
+                tries=$$((tries+1))
+                sleep $$sleep_time
+            done
+        }
+
+        echo "Starting Syncthing in the background"
+        /bin/entrypoint.sh /bin/syncthing &
+        SYNCTHING_PID=$$!
+        echo "Syncthing started with PID [$$SYNCTHING_PID]"
+        echo "Waiting for Syncthing to be ready..."
+
+        try_for 15 2 "[ -f '{{ config_dir }}/config.xml' ]" || { echo "Syncthing did not become ready in time. Exiting..."; exit 1; }
+        try_for 15 2 "curl --silent --output /dev/null http://127.0.0.1:{{ values.network.web_port }}/rest/noauth/health" || { echo "Syncthing did not become ready in time. Exiting..."; exit 1; }
+        echo "Syncthing is ready."
+
+      {% for cfg in settings %}
+        echo 'Using subcommand [{{ cfg.cmd }}] to set value [{{ '\"%s\"' | format(cfg.value) if cfg.quote else cfg.value }}]'
+        {{ cli }} {{ cfg.cmd }} set -- {{ '"%s"' | format(cfg.value) if cfg.quote else cfg.value }} || { echo "Failed to apply. Exiting..."; exit 1; }
+      {% endfor %}
+
+        echo "Gracefully stopping Syncthing..."
+        kill -SIGTERM $$SYNCTHING_PID
+        wait $$SYNCTHING_PID
+        echo "Syncthing stopped."
+
+    environment: {{ ix_lib.base.environment.envs(app=app_env, user=values.syncthing.additional_envs, values=values) | tojson }}
+    volumes: {{ volume_mounts.items | tojson }}
   {{ values.consts.syncthing_container_name }}:
     image: {{ ix_lib.base.utils.get_image(images=values.images, name="image") }}
     user: "0:0"
@@ -43,13 +140,15 @@ services:
     deploy:
       resources: {{ ix_lib.base.resources.resources(values.resources) | tojson }}
     devices: {{ ix_lib.base.resources.get_devices(values.resources) | tojson }}
-    {% set caps = ix_lib.base.security.get_caps(add=["CHOWN", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID", "SETFCAP", "SETPCAP", "SYS_ADMIN"]) %}
     cap_add: {{ caps.add | tojson }}
     cap_drop: {{ caps.drop | tojson }}
     security_opt: {{ ix_lib.base.security.get_sec_opts(remove=["no-new-privileges"]) | tojson }}
     {% if values.network.host_network %}
     network_mode: host
     {% endif %}
+    depends_on:
+      {{ values.consts.config_container_name }}:
+        condition: service_completed_successfully
     {% if values.network.dns_opts %}
     dns_opt: {{ ix_lib.base.network.dns_opts(values.network.dns_opts) | tojson }}
     {% endif %}
@@ -65,12 +164,7 @@ services:
     {% set test = ix_lib.base.healthchecks.wget_test(port=values.network.web_port, path="/rest/noauth/health") %}
     healthcheck: {{ ix_lib.base.healthchecks.check_health(test) | tojson }}
     volumes: {{ volume_mounts.items | tojson }}
-    environment: {{ ix_lib.base.environment.envs(app={
-      "PCAP": ["cap_sys_admin", "cap_chown", "cap_dac_override", "cap_fowner"]|join(",") + "+ep",
-      "STNOUPGRADE": true,
-      "STGUIADDRESS": "0.0.0.0:%d" | format(values.network.web_port),
-      "STGUIASSETS": "/var/truenas/assets/gui",
-    }, user=values.syncthing.additional_envs, values=values) | tojson }}
+    environment: {{ ix_lib.base.environment.envs(app=app_env, user=values.syncthing.additional_envs, values=values) | tojson }}
     {% if not values.network.host_network %}
     ports:
       - {{ ix_lib.base.ports.get_port(port={"target": values.network.web_port, "published": values.network.web_port}) | tojson }}
