a bit more logging

diff --git a/ix-dev/community/palworld/templates/docker-compose.yaml b/ix-dev/community/palworld/templates/docker-compose.yaml
--- a/ix-dev/community/palworld/templates/docker-compose.yaml
+++ b/ix-dev/community/palworld/templates/docker-compose.yaml
@@ -104,7 +104,7 @@ services:
         if [ ! -f {{ cfg_file }} ]; then
           echo "Config file not found, fetching..."
           # -- Fetch the config file if it doesn't exist, just like the container does
-          wget -qO {{ cfg_file }} https://github.com/ich777/docker-steamcmd-server/raw/palworld/config/PalWorldSettings.ini || exit 1
+          wget -qO {{ cfg_file }} https://github.com/ich777/docker-steamcmd-server/raw/palworld/config/PalWorldSettings.ini || { echo "Failed to fetch config file"; exit 1; }
         fi
 
         set_ini_value() {
@@ -145,6 +145,7 @@ services:
         set_ini_value "AdminPassword" '{{ values.palworld.admin_password }}' true false
         set_ini_value "AllowConnectPlatform" '{{ values.palworld.allow_platform }}' false
 
+        echo "Setting user defined ini keys..."
         {% for item in values.palworld.ini_keys %}
           {% set key = item.key %}
           {% set value = item.value|string %}
