fix config path and make it fail if something goes wrong

diff --git a/ix-dev/community/palworld/templates/docker-compose.yaml b/ix-dev/community/palworld/templates/docker-compose.yaml
--- a/ix-dev/community/palworld/templates/docker-compose.yaml
+++ b/ix-dev/community/palworld/templates/docker-compose.yaml
@@ -100,11 +100,13 @@ services:
           echo "Config directory not found, creating..."
           mkdir -p {{ cfg }}
         fi
+
         if [ ! -f {{ cfg_file }} ]; then
           echo "Config file not found, fetching..."
           # -- Fetch the config file if it doesn't exist, just like the container does
-          wget -qO {{ cfg_file }} https://github.com/ich777/docker-steamcmd-server/raw/palworld/config/PalWorldSettings.ini
+          wget -qO {{ cfg_file }} https://github.com/ich777/docker-steamcmd-server/raw/palworld/config/PalWorldSettings.ini || exit 1
         fi
+
         set_ini_value() {
           local key="$${1}"
           local value="$${2}"
@@ -116,19 +118,21 @@ services:
             escaped_value="\"$${escaped_value}\""
           fi
 
-          echo "Setting $${key}..."
+          echo -n "Setting $${key}..."
 
           # Check if the key already exists
-          if grep -q "^OptionSettings=\(.*$${key}=.*\)$$" "$${cfgFile}"; then
+          if grep -q "^OptionSettings=\(.*$${key}=.*\)$$" "{{ cfg_file }}"; then
               # Key exists, update its value using the original logic
-              sed -i "s|\($${key}=\)[^,]*|\1$${escaped_value}|g" "$${cfgFile}"
+              sed -i "s|\($${key}=\)[^,]*|\1$${escaped_value}|g" "{{ cfg_file }}" || { echo "Failed to update $${key}"; exit 1; }
           else
               # Key doesn't exist, append it right after "OptionSettings=("
-              sed -i "s|^\(OptionSettings=(\)|\1$${key}=$${escaped_value}, |" "$${cfgFile}"
+              sed -i "s|^\(OptionSettings=(\)|\1$${key}=$${escaped_value}, |" "{{ cfg_file }}" || { echo "Failed to append $${key}"; exit 1; }
           fi
 
           if [ "$$print" = true ]; then
-            echo "Set to $$(grep -Po "(?<=$${key}=)[^,]*" "{{ cfg_file }}")"
+            echo " Set to $$(grep -Po "(?<=$${key}=)[^,]*" "{{ cfg_file }}")" || { echo "Failed to print $${key}"; exit 1; }
+          else
+            echo " Set, but value is marked as private"
           fi
         }
 
