better handing

diff --git a/ix-dev/community/archisteamfarm/ix_values.yaml b/ix-dev/community/archisteamfarm/ix_values.yaml
--- a/ix-dev/community/archisteamfarm/ix_values.yaml
+++ b/ix-dev/community/archisteamfarm/ix_values.yaml
@@ -14,7 +14,8 @@ consts:
   entrypoint: |
     #!/bin/sh
     set -e
-    echo "Copying IPC config..."
-    cp /config/IPC.config /app/config/IPC.config
+    [ -f /app/config/IPC.config ] && { echo "Removing old IPC config..."; rm /app/config/IPC.config; }
+    echo "Copying updated IPC config..."
+    cp /config/IPC.config /app/config/IPC.config || { echo "Failed to copy IPC config"; exit 1; }
     echo "Starting ArchiSteamFarm..."
     exec ArchiSteamFarm --no-restart --system-required
