Publish new changes in catalog [skip ci]

diff --git a/trains/community/archisteamfarm/1.0.1/ix_values.yaml b/trains/community/archisteamfarm/1.0.1/ix_values.yaml
--- a/trains/community/archisteamfarm/1.0.1/ix_values.yaml
+++ b/trains/community/archisteamfarm/1.0.1/ix_values.yaml
@@ -1,7 +1,7 @@
 images:
   image:
     repository: ghcr.io/justarchinet/archisteamfarm
-    tag: 6.1.4.2
+    tag: 6.1.4.3
 
 consts:
   archisteamfarm_container_name: archisteamfarm
@@ -14,7 +14,8 @@ consts:
   entrypoint: |
     #!/bin/sh
     set -e
-    echo "Copying IPC config..."
-    cp /config/IPC.config /app/config/IPC.config
+    [ -f /app/config/IPC.config ] && { echo "Removing old IPC config..."; rm /app/config/IPC.config; }
+    echo "Copying updated IPC config..."
+    cp /config/IPC.config /app/config/IPC.config || { echo "Failed to copy IPC config"; exit 1; }
     echo "Starting ArchiSteamFarm..."
     exec ArchiSteamFarm --no-restart --system-required
