briefkasten: use v2 (#965)
* briefkasten: use v2

* add lib

* fixe

* perms container

* fix init

diff --git a/ix-dev/community/briefkasten/templates/docker-compose.yaml b/ix-dev/community/briefkasten/templates/docker-compose.yaml
--- a/ix-dev/community/briefkasten/templates/docker-compose.yaml
+++ b/ix-dev/community/briefkasten/templates/docker-compose.yaml
@@ -1,151 +1,95 @@
-{# Stores storage items that contains info for volumes, vol mounts, perms dirs and perms mounts #}
-{% set storage_items = namespace(items=[]) %}
-{% set pg_storage_items = namespace(items=[]) %}
-{# Stores the top level volumes #}
-{% set volumes = namespace(items={}) %}
-{# Stores the container volume mounts #}
-{% set volume_mounts = namespace(items=[]) %}
-{# Stores the postgres volume mounts #}
-{% set pg_volume_mounts = namespace(items=[]) %}
-{# Stores the perms container volume mounts #}
-{% set perms_mounts = namespace(items=[]) %}
-{# Stores the perms container dirs #}
-{% set perms_dirs = namespace(items=[]) %}
+{% set tpl = ix_lib.base.render.Render(values) %}
 
-{% do storage_items.items.append(ix_lib.base.storage.storage_item(data={"type":"anonymous", "mount_path": "/tmp"})) %}
+{% set c1 = tpl.add_container(values.consts.briefkasten_container_name, "image") %}
+{% set init = tpl.add_container(values.consts.init_container_name, "image") %}
+{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
 
+{% set pg_config = {
+  "user": values.consts.db_user,
+  "password": values.briefkasten.postgres_password,
+  "database": values.consts.db_name,
+  "volume": values.storage.postgres_data,
+} %}
+{% set postgres = tpl.deps.postgres(values.consts.pg_container_name, "postgres_image", pg_config, perm_container) %}
+
+{% set envs = namespace(x={
+  "PORT": values.network.web_port,
+  "NODE_ENV": "production",
+  "DATABASE_URL": postgres.get_url("postgres"),
+  "NEXTAUTH_SECRET": values.briefkasten.nextauth_secret,
+  "NEXTAUTH_URL": values.briefkasten.nextauth_url,
+  "NEXTAUTH_URL_INTERNAL": "http://127.0.0.1:%d"|format(values.network.web_port),
+}) %}
+
+{% if values.briefkasten.smtp.enabled and envs.x.update({
+  "SMTP_HOST": values.briefkasten.smtp.server,
+  "SMTP_FROM": values.briefkasten.smtp.from
+}) %}{% endif %}
+
+{% if values.briefkasten.github.enabled and envs.x.update({
+  "GITHUB_ID": values.briefkasten.github.id,
+  "GITHUB_SECRET": values.briefkasten.github.secret
+}) %}{% endif %}
+
+{% if values.briefkasten.google.enabled and envs.x.update({
+  "GOOGLE_ID": values.briefkasten.google.id,
+  "GOOGLE_SECRET": values.briefkasten.google.secret
+}) %}{% endif %}
+
+{% if values.briefkasten.keycloak.enabled and envs.x.update({
+  "KEYCLOAK_NAME": values.briefkasten.keycloak.name,
+  "KEYCLOAK_ID": values.briefkasten.keycloak.id,
+  "KEYCLOAK_SECRET": values.briefkasten.keycloak.secret,
+  "KEYCLOAK_ISSUER": values.briefkasten.keycloak.issuer
+}) %}{% endif %}
+
+{% if values.briefkasten.authentik.enabled and envs.x.update({
+  "AUTHENTIK_NAME": values.briefkasten.authentik.name,
+  "AUTHENTIK_ID": values.briefkasten.authentik.id,
+  "AUTHENTIK_SECRET": values.briefkasten.authentik.secret,
+  "AUTHENTIK_ISSUER": values.briefkasten.authentik.issuer
+}) %}{% endif %}
+
+{% do init.set_user(values.consts.run_user, values.consts.run_group) %}
+{% do init.depends.add_dependency(values.consts.pg_container_name, "service_healthy") %}
+{% do init.restart.set_policy("on-failure", 1) %}
+{% do init.deploy.resources.set_profile("low") %}
+{% do init.healthcheck.disable() %}
+{% do init.set_entrypoint(["/bin/sh", "-c"]) %}
+{% do init.set_command([
+  "echo 'Migrating database...'\n"
+  "pnpm db:push || (echo 'DB migration failed...' && exit 1)\n"
+  "echo 'Database migration complete. Application will now start'\n"
+]) %}
+
+{% do c1.set_user(values.consts.run_user, values.consts.run_group) %}
+{% do c1.depends.add_dependency(values.consts.pg_container_name, "service_healthy") %}
+{% do c1.depends.add_dependency(values.consts.init_container_name, "service_completed_successfully") %}
+{% do c1.healthcheck.set_test("tcp", {"port": values.network.web_port}) %}
+
+{% for key, value in envs.x.items() %}
+  {% do init.environment.add_env(key, value) %}
+  {% do c1.environment.add_env(key, value) %}
+{% endfor %}
+{% do init.environment.add_user_envs(values.briefkasten.additional_envs) %}
+{% do c1.environment.add_user_envs(values.briefkasten.additional_envs) %}
+
+{% set perms_config = {"uid": values.consts.run_user, "gid": values.consts.run_group, "mode": "check"} %}
 {% for store in values.storage.additional_storage %}
-  {% do storage_items.items.append(ix_lib.base.storage.storage_item(data=store, values=values,
-    perm_opts={"mount_path": "/mnt/briefkasten/dir_%s"|format(loop.index0), "mode": "check", "uid": values.consts.run_user, "gid": values.consts.run_group}
-  )) %}
+  {% do c1.add_storage(store.mount_path, store) %}
+  {% do init.add_storage(store.mount_path, store) %}
+  {% do perm_container.add_or_skip_action(store.mount_path, store, perms_config) %}
 {% endfor %}
 
-{# Add each item to the above lists #}
-{% for item in storage_items.items %}
-  {% if item.vol and volumes.items.update(item.vol) %}{% endif %}
-  {% if item.vol_mount and volume_mounts.items.append(item.vol_mount) %}{% endif %}
-  {% if item.perms_item and (perms_dirs.items.append(item.perms_item.perm_dir), perms_mounts.items.append(item.perms_item.vol_mount)) %}{% endif %}
-{% endfor %}
+{% do c1.ports.add_port(values.network.web_port, values.network.web_port) %}
 
-{% do pg_storage_items.items.append(ix_lib.base.storage.storage_item(data={"type":"anonymous", "mount_path": "/tmp"})) %}
-{% do pg_storage_items.items.append(ix_lib.base.storage.storage_item(data=dict(values.storage.postgres_data, **{"mount_path": "/var/lib/postgresql/data"}),
-  values=values, perm_opts={"mount_path": "/mnt/postgres/data", "mode": "check", "uid": values.consts.pg_run_user, "gid": values.consts.pg_run_group}
-)) %}
-
-{% for item in pg_storage_items.items %}
-  {% if item.vol and volumes.items.update(item.vol) %}{% endif %}
-  {% if item.vol_mount and pg_volume_mounts.items.append(item.vol_mount) %}{% endif %}
-  {% if item.perms_item and (perms_dirs.items.append(item.perms_item.perm_dir), perms_mounts.items.append(item.perms_item.vol_mount)) %}{% endif %}
-{% endfor %}
-{% set app_env = ix_lib.base.utils.merge_dicts({
-    "DATABASE_URL": ix_lib.base.postgres.pg_url(
-      variant="postgres", host=values.consts.pg_container_name, user=values.consts.pg_user,
-      password=values.briefkasten.postgres_password, dbname=values.consts.pg_database
-    ),
-    "NEXTAUTH_SECRET": values.briefkasten.nextauth_secret,
-    "NEXTAUTH_URL": values.briefkasten.nextauth_url,
-    "PORT": values.network.web_port,
-    "NODE_ENV": "production",
-    "NEXTAUTH_URL_INTERNAL": "http://127.0.0.1:%d"|format(values.network.web_port),
-  },{
-    "SMTP_HOST": values.briefkasten.smtp.server,
-    "SMTP_FROM": values.briefkasten.smtp.from,
-  } if values.briefkasten.smtp.enabled else {}, {
-    "GITHUB_ID": values.briefkasten.github.id,
-    "GITHUB_SECRET": values.briefkasten.github.secret,
-  } if values.briefkasten.github.enabled else {}, {
-    "GOOGLE_ID": values.briefkasten.google.id,
-    "GOOGLE_SECRET": values.briefkasten.google.secret,
-  } if values.briefkasten.google.enabled else {}, {
-    "KEYCLOAK_NAME": values.briefkasten.keycloak.name,
-    "KEYCLOAK_ID": values.briefkasten.keycloak.id,
-    "KEYCLOAK_SECRET": values.briefkasten.keycloak.secret,
-    "KEYCLOAK_ISSUER": values.briefkasten.keycloak.issuer,
-  } if values.briefkasten.keycloak.enabled else {}, {
-    "AUTHENTIK_NAME": values.briefkasten.authentik.name,
-    "AUTHENTIK_ID": values.briefkasten.authentik.id,
-    "AUTHENTIK_SECRET": values.briefkasten.authentik.secret,
-    "AUTHENTIK_ISSUER": values.briefkasten.authentik.issuer,
-  } if values.briefkasten.authentik.enabled else {},
-) %}
-
-{# Containers #}
-services:
-  {{ values.consts.init_container_name }}:
-    image: {{ ix_lib.base.utils.get_image(images=values.images, name="image") }}
-    user: {{ "%d:%d" | format(values.consts.run_user, values.consts.run_group) }}
-    deploy:
-      resources:
-        limits:
-          cpus: "1.0"
-          memory: 512m
-    depends_on:
-      {{ values.consts.pg_container_name }}:
-        condition: service_healthy
-    entrypoint:
-      - /bin/sh
-      - -c
-    command:
-      - |
-        echo "Migrating database"
-        pnpm db:push || (echo "DB migration failed..." && exit 1)
-        echo "DB migration successful. Application will now start"
-        exit 0
-    environment: {{ ix_lib.base.environment.envs(app=app_env, user=values.briefkasten.additional_envs, values=values) | tojson }}
-    volumes: {{ volume_mounts.items | tojson }}
-
-  {{ values.consts.briefkasten_container_name }}:
-    user: {{ "%d:%d" | format(values.consts.run_user, values.consts.run_group) }}
-    image: {{ ix_lib.base.utils.get_image(images=values.images, name="image") }}
-    restart: unless-stopped
-    links:
-      - {{ values.consts.pg_container_name }}
-    deploy:
-      resources: {{ ix_lib.base.resources.resources(values.resources) | tojson }}
-    devices: {{ ix_lib.base.resources.get_devices(values.resources) | tojson }}
-    depends_on:
-      {{ values.consts.pg_container_name }}:
-        condition: service_healthy
-      {{ values.consts.init_container_name }}:
-        condition: service_completed_successfully
-    {% if perms_dirs.items %}
-      {{ values.consts.perms_container_name }}:
-        condition: service_completed_successfully
-    {% endif %}
-    cap_drop: {{ ix_lib.base.security.get_caps().drop | tojson }}
-    security_opt: {{ ix_lib.base.security.get_sec_opts() | tojson }}
-    {% if values.network.dns_opts %}
-    dns_opt: {{ ix_lib.base.network.dns_opts(values.network.dns_opts) | tojson }}
-    {% endif %}
-    {% set test = ix_lib.base.healthchecks.tcp_test(port=values.network.web_port) %}
-    healthcheck: {{ ix_lib.base.healthchecks.check_health(test) | tojson }}
-    environment: {{ ix_lib.base.environment.envs(app=app_env, user=values.briefkasten.additional_envs, values=values) | tojson }}
-    ports:
-      - {{ ix_lib.base.ports.get_port(port={"target": values.network.web_port, "published": values.network.web_port}) | tojson }}
-    volumes: {{ volume_mounts.items | tojson }}
-  {% if perms_dirs.items %}
-  {{ values.consts.perms_container_name }}: {{ ix_lib.base.permissions.perms_container(items=perms_dirs.items, volumes=perms_mounts.items) | tojson }}
-  {% endif %}
-
-  {% set resource_without_gpus = ix_lib.base.utils.copy_dict(values.resources) %}
-  {% do resource_without_gpus.pop("gpus", None) %}
-  {{ values.consts.pg_container_name }}: {{ ix_lib.base.postgres.pg_container(data={
-    "image": ix_lib.base.utils.get_image(images=values.images, name="postgres_image"),
-    "volumes": pg_volume_mounts.items,
-    "user": values.consts.pg_run_user, "group": values.consts.pg_run_group,
-    "db_user": values.consts.pg_user, "db_name": values.consts.pg_database,
-    "db_password": values.briefkasten.postgres_password,
-    "dns_opt": values.network.dns_opts, "resources": resource_without_gpus,
-    "depends_on": {
-      values.consts.perms_container_name: {
-        "condition": "service_completed_successfully"
-      }
-    }
-  }) | tojson }}
-
-{% if volumes.items %}
-volumes: {{ volumes.items | tojson }}
+{% if perm_container.has_actions() %}
+  {% do perm_container.activate() %}
+  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
+  {% do init.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
+  {% do postgres.container.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
 {% endif %}
 
-x-portals: {{ ix_lib.base.metadata.get_portals([{"port": values.network.web_port}]) | tojson }}
-x-notes: {{ ix_lib.base.metadata.get_notes("Briefkasten") | tojson }}
+{% do tpl.portals.add_portal({"port": values.network.web_port}) %}
+
+{{ tpl.render() | tojson }}
