add migration

diff --git a/ix-dev/stable/storj/templates/docker-compose.yaml b/ix-dev/stable/storj/templates/docker-compose.yaml
--- a/ix-dev/stable/storj/templates/docker-compose.yaml
+++ b/ix-dev/stable/storj/templates/docker-compose.yaml
@@ -57,7 +57,7 @@ services:
       {{ values.consts.perms_container_name }}:
         condition: service_completed_successfully
     {% endif %}
-    environment: {{ ix_lib.base.environment.envs(app=dict(app_env, **{"AUTH_KEY": values.storj.auth_key|string}), user=values.storj.additional_envs, values=values) | tojson }}
+    environment: {{ ix_lib.base.environment.envs(app=dict(app_env, **{"AUTH_TOKEN": values.storj.auth_token|string}), user=values.storj.additional_envs, values=values) | tojson }}
     entrypoint:
       - sh
       - -c
@@ -78,7 +78,7 @@ services:
           {{ id_tool_dir }}/identity create storagenode || { echo "Failed to generate identity certificate."; exit 1; }
 
           echo "Authorizing identity certificate..."
-          {{ id_tool_dir }}/identity authorize storagenode $${AUTH_KEY} || { echo "Failed to authorize identity certificate."; exit 1; }
+          {{ id_tool_dir }}/identity authorize storagenode $${AUTH_TOKEN} || { echo "Failed to authorize identity certificate."; exit 1; }
 
           echo "Storagenode identity certificate generated successfully."
         else
