cleanup after app run

diff --git a/.github/workflows/install-docker.yaml b/.github/workflows/install-docker.yaml
--- a/.github/workflows/install-docker.yaml
+++ b/.github/workflows/install-docker.yaml
@@ -69,7 +69,7 @@ jobs:
         run: |
           for values_file in ix-dev/${{ matrix.app }}/ci/*.yaml; do
             echo "Testing [$values_file]"
-            ./main.py $values_file ix-dev/${{ matrix.app }} > docker-compose.yaml
+            sudo ./main.py $values_file ix-dev/${{ matrix.app }} > docker-compose.yaml
 
             # Print the parsed, by compose, template
             # (as it will also remove empty lines)
@@ -83,4 +83,8 @@ jobs:
 
             docker compose -p $PROJECT_NAME -f docker-compose.yaml down --remove-orphans --volumes
             docker compose -p $PROJECT_NAME -f docker-compose.yaml rm --force --stop --volumes
+
+            # Clean up the test directory used by the app
+            echo "Cleaning up /mnt/test directory"
+            sudo rm -r /mnt/test || echo "Failed to clean up /mnt/test"
           done
