message

diff --git a/.github/workflows/install-docker.yaml b/.github/workflows/install-docker.yaml
--- a/.github/workflows/install-docker.yaml
+++ b/.github/workflows/install-docker.yaml
@@ -85,5 +85,6 @@ jobs:
             docker compose -p $PROJECT_NAME -f docker-compose.yaml rm --force --stop --volumes
 
             # Clean up the test directory used by the app
-            sudo rm -r /mnt/test
+            echo "Cleaning up /mnt/test directory"
+            sudo rm -r /mnt/test || echo "Failed to clean up /mnt/test"
           done
